import Head from 'next/head'
import Image from 'next/image'
import Arguments from '../Components/Sections/Home/Arguments/Arguments'
import Banner from '../Components/Sections/Home/Banner/Banner'
import BrandBanner from '../Components/Sections/Home/BrandBanner/BrandBanner'
import Cars from '../Components/Sections/Home/Cars/Cars'
import Comfort from '../Components/Sections/Home/Comfort/Comfort'
import Workflow from '../Components/Sections/Home/Workflow/Workflow'
import Title from '../Theme/Title/Title'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
       <Banner/>
       <BrandBanner/>
       <Workflow/>
       <Arguments/>
       <Cars/>
       <Comfort/>
      </main>
    </div>
  )
}
